name = "barber-brothers"
compatibility_date = "2026-04-30"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "barber-brothers-db"
database_id = "1fd74c5a-6bf8-4356-aadb-422c716a4186"
migrations_dir = "migrations"
