name = "barber-brothers"
compatibility_date = "2026-04-30"
pages_build_output_dir = "out"

[vars]
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyBFCFMufU9FHQ0emIA3UaL3UXPynLSGGeY"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "barber-brothers-3786c.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "barber-brothers-3786c"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "barber-brothers-3786c.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "490091607279"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:490091607279:web:32b69e87e6059b7f2f971a"
